-- Even Fibonacci numbers
-- Problem 2
-- Each new term in the Fibonacci sequence is generated by adding the previous two terms.
-- By starting with 1 and 2, the first 10 terms will be:
--
-- 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
--
-- By considering the terms in the Fibonacci sequence whose values do not exceed four million,
-- find the sum of the even-valued terms.

main = do
    print (fib 1 1 0)

fib f f2 s =
    if f2 <= 4000001 then
        if f2 `mod` 2 == 0 then
            fib f2 (f + f2) (f2 + s)
        else
            fib f2 (f + f2) s
    else
        s
